const bodyBg = prompt("Enter body background color");
const textColor = prompt("Enter text color");

document.body.style.backgroundColor = bodyBg;

const paragraph = document.createElement("p");
paragraph.style.color = textColor;

paragraph.textContent = `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia, aut voluptatem ad eveniet cupiditate praesentium provident architecto ipsam nam pariatur, ea nemo dolore autem minima consectetur maiores esse non quaerat.
    Modi consectetur culpa dicta maiores animi perspiciatis doloribus mollitia fuga recusandae minima! Sed nobis doloribus excepturi? Placeat, ex veniam adipisci, exercitationem error accusantium velit repellendus non temporibus qui deleniti pariatur.
    Nisi, vero! Consequuntur, numquam debitis ipsa alias suscipit soluta autem laboriosam cum mollitia repudiandae sit adipisci cumque eligendi recusandae temporibus facere placeat esse, nesciunt, obcaecati nihil nulla doloremque laudantium nam?
    Iure unde, reiciendis nulla eveniet assumenda et! Mollitia, voluptatem. Eius, tenetur. Fuga mollitia fugit accusamus iusto quasi. Amet aliquid quos placeat aliquam quaerat accusamus quis sunt, pariatur molestiae corrupti obcaecati.
    Ipsa dolore voluptas optio modi officiis accusamus doloribus esse laboriosam architecto perferendis rem fuga explicabo neque, molestiae ut amet, cumque velit et? Quae possimus nobis, quas perferendis id error reprehenderit!
    Repellat incidunt cupiditate ad quisquam voluptatum animi itaque inventore amet natus commodi quo corporis, nam adipisci quas consequatur quae nihil autem quidem aliquam! Delectus facere quas quia quisquam, aliquam rerum?
    Autem tempora totam quia et, nesciunt eveniet omnis doloremque laborum consequuntur. Quibusdam, nobis distinctio, vero ipsam necessitatibus molestiae consequatur esse vel sunt excepturi aspernatur exercitationem rem? Doloremque, nihil. Architecto, explicabo!
    Necessitatibus architecto in a odit maiores soluta pariatur illo doloremque nobis tempora et, alias reiciendis accusantium obcaecati voluptates facilis sapiente nulla. Assumenda labore cupiditate culpa laboriosam nemo blanditiis facere earum?
    Doloremque temporibus voluptas accusamus reiciendis iusto delectus nesciunt consectetur velit, vitae, ratione ipsum provident labore atque totam praesentium recusandae laboriosam deserunt molestias officiis! Consequatur dolorum, reprehenderit cum quisquam vero ut.
    Itaque amet velit porro deleniti nobis modi, dolore distinctio aliquid, adipisci qui maxime omnis sed vel illo rem consequuntur quis facere, sunt molestias libero quam error dolor. Tempora, numquam officiis.
    Commodi, minima. Nemo aliquam pariatur facere illum. Soluta sint sapiente officiis voluptate. Quis repellat, dicta, debitis reprehenderit cupiditate doloribus vitae nam et laboriosam ea quibusdam consequatur tempora minima omnis officia!
    Dolore optio necessitatibus incidunt quam eos placeat voluptates nisi iste ratione. Laborum doloribus incidunt ut a soluta! Consequuntur veniam tenetur minima animi, recusandae aliquid facere tempore. Sequi vero ipsam possimus.
    Non quibusdam exercitationem quasi ex atque. Enim, ab a. Ex magnam hic facilis dolorem quo aperiam at dolor eius ipsum, sapiente cumque accusantium nihil tempore non, corporis rerum deleniti fugit!
    Dolorum impedit officia assumenda fugiat neque sapiente quisquam magni provident. Porro, recusandae! Quae itaque aspernatur esse sed in totam facere labore perferendis magnam maiores sunt libero, laboriosam mollitia expedita minima?
    Temporibus nobis sed explicabo consectetur. Vel ipsam laboriosam maxime et? Facilis incidunt nam eaque facere inventore eligendi delectus corporis temporibus, dolor, officiis ipsam doloribus! A sed molestiae delectus laborum minima.
    Consequuntur saepe eaque maiores. Neque, aut? Molestias deserunt quidem odit cupiditate, perspiciatis possimus doloremque architecto impedit, ratione eligendi enim earum nemo, facilis iusto vel veritatis minima aperiam alias? Sequi, similique.
    Maiores, minima sed nam accusantium dignissimos cupiditate deserunt tenetur! Pariatur perspiciatis possimus impedit libero numquam natus deleniti esse, quidem facere iste veniam ipsum, accusamus ea non magnam minima. Laborum, quisquam.
    Dolorem architecto modi est animi dignissimos qui velit non labore illo, quam sunt cupiditate ipsam maxime a praesentium, reprehenderit maiores ad expedita numquam voluptatum incidunt nemo molestiae? Quisquam, laboriosam totam.
    Ut, voluptas quia? Mollitia delectus sint facilis, saepe ea magni deserunt ut consequuntur corrupti eaque eveniet nam voluptatibus nostrum, accusamus omnis adipisci nobis consectetur. Sunt optio animi rerum aliquid veritatis?
    Consequuntur explicabo, pariatur ullam temporibus dolore numquam quibusdam ex, quod error, rerum amet autem quo sed. Unde, aliquid cum dolores laudantium laborum dicta, quos illum adipisci voluptas iure, error natus!
    Ab voluptate sequi consectetur, obcaecati quos delectus et, ipsam expedita quaerat perspiciatis cumque placeat distinctio veritatis corrupti nihil natus eos quas! Laborum ut culpa dolorem harum a amet ipsam nulla.
    Aliquid unde molestias provident perspiciatis qui debitis itaque asperiores alias placeat ea fugiat ullam omnis eum incidunt dicta ex tenetur fugit non expedita minima, repellat in. Ipsa culpa eius quia?
    Molestias quisquam nam iste quidem, facilis cupiditate quis autem deleniti id dicta assumenda voluptatem accusantium voluptatum, vitae qui doloremque tempore veritatis obcaecati numquam dolore accusamus. Molestias a illum amet iusto?
    Dolor modi quisquam fuga sequi cum sed itaque nihil esse quaerat dolorem dolore in voluptatum facilis expedita laborum laboriosam delectus, unde odit nobis debitis vel. Harum molestias soluta dolorem natus!
    Praesentium optio, sint modi numquam veniam dignissimos vel architecto rerum hic quasi cupiditate, aperiam repellendus officia placeat laboriosam corrupti consectetur illo eveniet dicta minus enim fuga expedita repellat delectus! Nemo!
    Obcaecati doloremque, quos ex soluta perspiciatis quis eos corporis, repudiandae perferendis cum repellendus blanditiis maxime ratione esse totam. Molestias dolores, corrupti consequatur quos nulla consequuntur omnis eos voluptatum totam consectetur.
    Consectetur est id repellendus placeat dolore tempora expedita nesciunt culpa quis nulla neque veniam amet eaque vero odit iste, accusamus eligendi fugit reiciendis voluptatibus assumenda vitae cupiditate aliquid aspernatur! Quo!
    Ipsum, enim dolorem. Quisquam natus minus odit dolorum dolores sequi. Placeat delectus, quibusdam voluptatum accusantium, eum, necessitatibus aperiam quae est neque iure quidem! Doloremque beatae optio minima itaque odit quo?
    Ut voluptates laudantium voluptate quas exercitationem. Natus voluptatem aspernatur labore hic numquam repellendus quisquam dolore obcaecati. In dolor harum, ut et non exercitationem eos voluptates at temporibus beatae impedit dolorum.
    Maiores, ipsum aliquam a corporis unde omnis? Molestiae tenetur veniam consectetur quibusdam blanditiis libero, odio alias molestias voluptates at ratione eum ut! Culpa, eaque fugiat velit expedita enim sit quae?
    Optio praesentium dicta sequi eveniet, architecto voluptate deserunt dolorum laborum amet tempora est beatae minima dolores corporis, rerum harum quam assumenda ab placeat asperiores fugiat facere pariatur incidunt! Id, omnis!
    Ipsa nam deserunt, voluptatibus aperiam delectus optio adipisci quo iure! Cupiditate perferendis quas obcaecati, dignissimos quo unde eius doloribus doloremque illum, voluptatum tempora praesentium, magni consequatur est vel minima quibusdam.
    Assumenda debitis suscipit culpa vero et, soluta quasi odio repellendus ad. Officia delectus quos deleniti reprehenderit rem sed eveniet, id laudantium voluptates libero nemo modi, corporis earum vero ipsam? Accusantium?
    Quam adipisci quaerat eum atque voluptates animi magnam error, consequuntur, laborum temporibus eos laboriosam rem voluptatum illo provident quidem mollitia, sunt veritatis sapiente fugit ipsum cupiditate suscipit porro sit. Nam.
    Pariatur sed, sunt est numquam excepturi maiores maxime similique quis optio veniam praesentium ex harum ea quo nulla assumenda non. Corrupti deleniti provident commodi, minus quidem veritatis beatae impedit assumenda.
    Quis necessitatibus facilis unde molestias nam veniam quaerat corporis laboriosam, consequatur nihil dolore consectetur illo vel facere nisi, repellat illum ipsa recusandae. Perferendis hic, maiores dicta sint impedit cum fuga.
    Provident vel aliquid sequi iure eius nemo et deserunt quasi, dicta totam nulla distinctio officia possimus culpa ea blanditiis tempore. Eaque sunt similique dolore ex expedita esse itaque in maiores.
    Ipsam itaque et dolor eos earum ipsum consequatur sunt quasi corporis saepe, dolore omnis ducimus aperiam animi modi iste praesentium quibusdam vero explicabo doloremque ex. Nostrum sapiente et saepe molestias.
    Illum distinctio maxime id voluptatibus, voluptatem neque reiciendis a nam recusandae, quasi totam. Eligendi tempora a odio qui possimus ut alias illo? Nesciunt asperiores, provident facere repellat ratione sed hic.
    Asperiores ducimus laboriosam quisquam id maxime adipisci consequatur officiis fuga neque excepturi qui, cupiditate sed quos consectetur animi corporis dignissimos odio quaerat? Sunt perferendis ipsa, praesentium inventore sapiente placeat harum.
    Adipisci quos enim cumque eligendi saepe dolore dolores alias facere maiores expedita, ad voluptates rerum beatae modi ullam dolorem ratione consectetur delectus. Natus aliquid, doloribus beatae unde optio eaque quis.
    Odit perspiciatis non illo officia explicabo iure earum culpa error vitae nostrum quam necessitatibus veritatis alias, facere quaerat porro nulla ipsam dolorum, dicta, aperiam excepturi. Magni harum cumque necessitatibus soluta!
    Repellat, ipsam! Maxime saepe unde amet beatae magnam molestias odio quia sed facilis eaque voluptatum quo at doloremque eum iusto, doloribus debitis quae, aliquam id. Molestias tempora dolore quisquam alias?
    Autem dolores sint minima, quasi numquam labore nobis, iusto quibusdam dolorem ipsam consequatur optio libero iste? Corporis quod laboriosam sapiente nobis explicabo assumenda similique doloribus, distinctio fugit libero quaerat recusandae!
    Ea soluta reprehenderit in tenetur beatae sit odit enim, impedit id hic repudiandae laboriosam, voluptas nobis cum, libero officia harum nulla deserunt numquam. Odit, quo doloribus maiores amet reprehenderit cumque.
    Quod distinctio voluptatum nam eius, labore fugiat velit architecto nobis? Expedita, molestiae quisquam vel totam quam odit, qui, error aut ipsam amet id nisi est praesentium molestias iusto aspernatur magnam.
    Odit impedit enim vero pariatur vitae, explicabo, perspiciatis sequi labore voluptatibus nulla, neque amet possimus laudantium mollitia iste. Nisi consequuntur eius odio, earum ratione cupiditate neque! Hic sit itaque eum.
    Asperiores officiis voluptates dolorem magni sint earum quasi. Ullam totam ut error itaque non reprehenderit, autem ea laudantium quae praesentium, nam atque quasi. Illum blanditiis adipisci veniam quas laboriosam voluptas!
    Laborum inventore vitae accusantium velit magnam blanditiis eveniet itaque est, illo in earum quisquam amet molestiae. Optio, dolore quos facilis mollitia repellendus impedit iste illum veritatis accusantium quia tempora! Aliquam?
    Quaerat, magnam suscipit voluptate quisquam tempora minus est repellendus veniam distinctio corrupti hic quis maiores ea soluta. Officiis voluptate sed vel quibusdam temporibus, voluptatum dolorum nisi libero suscipit vitae aspernatur!
    Animi, praesentium ipsa. Pariatur commodi ad similique, odit dolorem illum qui quibusdam fugiat ipsum veritatis dicta consequatur corporis non dolores voluptatum, itaque ab. Explicabo libero pariatur facilis omnis, quos cum!
    Recusandae expedita magnam, natus officiis quae eveniet tempora. Alias doloremque sed dolorem culpa quae! Obcaecati dolorum dolorem voluptate iusto porro corrupti in quam voluptates ullam saepe! Voluptatibus sed voluptas quia!
    Sapiente esse cumque nam? Velit id consequuntur quod molestias ratione, incidunt quisquam facere accusantium, esse obcaecati facilis officiis! Minus veritatis animi consequuntur illum aspernatur architecto consectetur, repudiandae eligendi dolores nisi!
    Minus sed corrupti officiis saepe fugiat reiciendis! Tempora a dolor beatae placeat assumenda voluptatum deleniti aspernatur quod voluptas maxime eius quis perspiciatis sequi quasi, dolores reiciendis fugit? Blanditiis, est impedit.
    Pariatur quia laudantium animi doloremque, vero aperiam. Quas, culpa voluptatem? Atque sint illum iure temporibus laudantium sunt aperiam, ullam minima harum eaque perspiciatis adipisci quas recusandae nostrum veritatis impedit doloribus!
    Cum doloremque quae neque numquam ullam facere optio voluptatibus odio molestiae quibusdam. Sequi aspernatur illum harum porro illo fuga, dolores architecto, molestiae nesciunt repellat, quo qui ad voluptates aliquid. Culpa.
    Voluptatibus quia, in commodi dignissimos quidem, eum obcaecati enim aliquid laboriosam mollitia eos, neque aperiam ut blanditiis dicta impedit magnam. Neque possimus, eius minus eveniet suscipit aliquam deleniti soluta nobis.
    Voluptatum obcaecati illum, accusamus cumque, aperiam optio excepturi nostrum facere corporis amet beatae molestiae, ipsam ad delectus eos quod dolores animi. Doloremque similique optio minima exercitationem asperiores incidunt doloribus quibusdam?
    Perspiciatis exercitationem, voluptates modi eius molestiae consequuntur cum dignissimos hic repudiandae, laboriosam incidunt eaque odio excepturi recusandae aliquid laborum blanditiis porro nemo eum, dolorem assumenda? Recusandae optio possimus fugit animi.
    Quisquam, laboriosam cumque nemo quasi quas nobis voluptate doloremque cupiditate nulla, libero sequi. Odio eum amet, libero illo impedit eos saepe harum, ducimus, delectus quo quae! Optio tempore iure temporibus?
    Impedit quod ab reprehenderit dolor porro alias distinctio repudiandae nesciunt natus est, vitae, nihil eveniet culpa suscipit reiciendis, debitis non! Aperiam sit vel sunt assumenda animi ipsa perspiciatis? Odio, sunt.
    Dolor recusandae soluta illum alias facere, labore necessitatibus sequi? Fugit eligendi hic architecto nisi natus iure soluta, doloribus quisquam molestias earum sunt repellendus incidunt at facere, iusto aspernatur dolorem aliquid.
    Beatae odit accusantium voluptas velit? Quasi vitae ducimus, quibusdam ut, aperiam soluta modi sint odio reiciendis maxime in dolores rerum dolore laudantium pariatur debitis. Consectetur culpa minus nisi. Sit, dolorum?
    Impedit, nisi a mollitia earum accusantium in id nulla! Quae, unde veniam libero distinctio eius, culpa accusantium eaque impedit tempore, animi odio blanditiis cumque! Ut harum inventore eius obcaecati saepe?
    Voluptatibus possimus excepturi, inventore at neque eaque odit praesentium maxime vel. Veniam nemo vel architecto atque repellendus fugit sequi et iusto cupiditate nostrum, ab quas nisi sit perferendis dolore odio?
    Veritatis, impedit. Necessitatibus molestiae sequi fuga ut voluptate, incidunt a? Deleniti vero nisi excepturi odio beatae ad. Eos magnam in quo vero aut fugit laudantium id harum totam ducimus. Corrupti?
    Voluptatibus eveniet perferendis pariatur molestias excepturi nam? Aut, maxime et. Sequi repudiandae fugit, atque veniam eligendi, ullam quas modi, doloremque veritatis sed blanditiis iure corrupti itaque accusamus quasi magnam nihil!
    Explicabo possimus non ratione perferendis hic qui aliquid nisi delectus voluptate harum molestias provident, iusto excepturi pariatur? Quo neque architecto earum modi quis aliquid, incidunt eius molestiae! Quasi, nobis eligendi.
    Voluptas et a nulla soluta explicabo facere repellendus nesciunt minima, nam corporis eligendi tempore provident autem cum cumque quas non error, dolores, deserunt ipsa itaque sapiente aliquam? Provident, enim quaerat.
    Adipisci minima, excepturi explicabo hic quia aliquid ducimus nulla illo beatae nostrum tempore quaerat nesciunt laudantium vel totam sequi eveniet, expedita dolorum delectus! Odit cumque sit optio nulla! Animi, adipisci.
    Reprehenderit iure iusto similique dignissimos molestiae architecto dicta voluptatem esse quam sunt, itaque aspernatur consequuntur quibusdam delectus laboriosam maiores animi debitis excepturi doloremque illum quos illo ab possimus. Error, eaque.
    At, hic quidem sunt laboriosam illo ipsa ipsum aspernatur quia excepturi beatae ab saepe perspiciatis dolor officiis veniam eaque, assumenda dignissimos, recusandae nulla maxime! Facilis necessitatibus architecto amet veniam alias.
    Accusantium officia voluptate quos, pariatur nesciunt, fugiat provident nemo dicta assumenda explicabo magni aperiam accusamus minus. Non optio quidem minus atque! Iusto rem officia, similique corrupti assumenda inventore perferendis odio!
    Harum deleniti sed, itaque labore distinctio explicabo nam ullam corrupti doloremque voluptate incidunt voluptatibus cupiditate sint quo sequi voluptatem autem aperiam, ad iusto, at hic quis quidem dolorem perspiciatis. Necessitatibus.
    Dolorum maxime est tempora asperiores voluptate quaerat quam voluptatum, dolore a? Accusamus, eaque ipsum dolorem praesentium necessitatibus quia itaque vel numquam beatae cum quod dolor sit dolores aperiam voluptate libero?
    Numquam iusto vitae modi rem aliquam consequuntur earum harum ad fuga magnam eos libero alias, cumque veniam atque amet voluptatibus maxime! Architecto a provident, numquam magnam aperiam nihil sapiente porro?
    Ipsa optio omnis praesentium, incidunt error nesciunt numquam, iste sapiente architecto doloribus nihil at magnam! Reprehenderit inventore cum perferendis veritatis voluptatum modi omnis repellendus laudantium consectetur! Sunt eveniet nesciunt magni!
    Nostrum adipisci sed omnis? Ut nobis corporis dolorem suscipit similique, nam cumque molestiae doloribus dolore. Repellendus earum illum amet non, possimus soluta atque asperiores. Velit consequatur molestiae minima nulla. Aliquid.
    Corporis est voluptatem nobis maiores aliquam quisquam, molestias tenetur iure earum doloremque laborum neque dolorum illum repellat consequuntur dolores libero consequatur ex, fugit nemo commodi qui. Reiciendis quis optio dolorum?
    Cum hic distinctio, maiores fugiat, sapiente veritatis nostrum quibusdam, perspiciatis itaque necessitatibus incidunt odit vitae et cumque atque maxime ipsum dolor a voluptate. Nemo nam assumenda repellendus voluptatum suscipit maiores!
    Cum exercitationem quo sit quasi! Totam, fugit voluptates consequuntur officia, sint odit et corporis alias officiis itaque architecto inventore! Molestiae fuga repellat sit modi aperiam, sint ipsum reprehenderit dolore rem.
    Tenetur, neque! Facilis eius, commodi iusto ducimus mollitia accusantium quod ipsum placeat, facere nostrum ad, aliquam quidem labore vero rem iure porro nam amet assumenda! Recusandae dignissimos autem inventore doloribus.
    Veniam quaerat in velit! Nam sunt rerum beatae illo quia doloribus, voluptatibus debitis eligendi modi consequuntur iure unde dolorem. Itaque facilis reprehenderit voluptates, non minima accusamus soluta consectetur ipsum voluptate?
    Vel officia inventore reprehenderit numquam, laboriosam temporibus dolorum perspiciatis quis vero eius itaque nisi iste. Suscipit est culpa, sint pariatur atque quam ipsam cum error, eos temporibus adipisci neque aliquam!
    Odio, laudantium. Illo magni consectetur minima distinctio obcaecati aut minus dolore, inventore animi odit beatae ducimus natus eligendi voluptatem commodi modi incidunt pariatur nobis? Mollitia rerum soluta itaque deserunt ratione?
    Odit alias ea iure accusantium, porro quod a voluptate consequuntur sint fuga qui similique error quis sunt dolore nisi provident at voluptatem aspernatur in sed natus. Suscipit reiciendis voluptatum quos?
    Nulla nisi quas consectetur corrupti alias fugit voluptatem adipisci expedita voluptate, laboriosam dolore error est. Nisi modi, est aut quos quaerat ex natus tempore inventore voluptatum rem culpa nihil iure.
    Saepe quod perspiciatis autem dicta doloremque esse magnam sequi! Sapiente facilis nulla similique, quas itaque quod cum ducimus eveniet ipsam quis consectetur esse voluptas numquam repudiandae, qui officia dicta eos!
    Hic, qui iure. Quaerat ex libero eum quae quos obcaecati eligendi eos dolore quidem. Nostrum excepturi quisquam velit aliquam, autem error, vel ipsum optio alias, enim quae. Voluptas, nesciunt error.
    Rem eveniet at, ipsam enim nostrum consequuntur non dolor repudiandae unde nihil inventore ullam dolorum libero vitae iusto assumenda odit autem odio maxime temporibus quidem esse! Nostrum consequuntur quod fugiat!
    Nostrum laudantium atque rem debitis illo aliquam itaque quibusdam dolores doloremque, exercitationem explicabo corrupti quam soluta animi, possimus, cumque quo maxime cupiditate laboriosam ratione recusandae fuga reiciendis magnam blanditiis! Numquam!
    Nisi rerum inventore quo! Voluptatem incidunt aliquam, omnis quisquam debitis eveniet? Suscipit, consectetur explicabo. Doloribus, fugit possimus magnam, reprehenderit quo, tempore maxime iure deserunt eaque a rem voluptas nihil accusantium!
    A, vel! Dignissimos culpa animi voluptatum, dolore vero illum, laboriosam voluptas assumenda ullam eum ipsam qui quam fugit exercitationem veritatis sed dolor quis! Dolores aspernatur tempora voluptatem quos excepturi quisquam!
    Beatae nesciunt quisquam ex ipsa fuga? Eius ipsam minima debitis sunt expedita quaerat possimus qui maiores pariatur laudantium rerum, deleniti commodi delectus fuga! Sint voluptatem quod numquam natus, consequatur corporis!
    Autem tenetur repudiandae unde id qui perferendis sapiente ullam culpa esse numquam animi repellendus vel rem maxime exercitationem aliquid molestias non quibusdam, laboriosam consectetur quam aperiam. Sunt cum ad eligendi!
    Consectetur, minus officiis! Pariatur corporis quisquam porro perferendis ad aliquid minus perspiciatis voluptates nobis temporibus quia blanditiis, nostrum quibusdam doloremque tempora quam quidem aliquam veniam iusto! Iure corporis quibusdam ad?
    Distinctio perspiciatis laboriosam impedit, ratione dignissimos velit porro veritatis magnam ab maiores sunt libero animi. Aut eum quia vitae nostrum, sapiente facilis? Illum consectetur magnam maxime quod esse nam earum.
    Recusandae cum illum a unde dolores molestiae est voluptate in temporibus, omnis dolorum rerum alias odio nostrum perferendis sit voluptatum quis odit. Maiores quam ducimus nemo corporis? Nobis, veniam provident.
    Corrupti adipisci sint modi in hic sunt, ipsum enim magnam earum fugit, aliquid optio recusandae impedit maiores vitae sit necessitatibus id asperiores ut minima dolorum. Reprehenderit impedit eveniet amet quaerat?
    Laborum itaque reiciendis soluta pariatur totam, assumenda voluptatum exercitationem, facilis numquam nobis temporibus in molestiae doloribus vitae neque sequi! Quod consequatur commodi soluta, possimus voluptates eum deleniti molestias consequuntur. Ex!`;

document.body.appendChild(paragraph);